config/routes.rb
Whatdo::Application.routes.draw do
  root "high_voltage/pages#show", id: "home"

  devise_for :users
  resources  :users, only: [:show]
  resources  :ideas do
    member do
      put :vote
    end
  end

  match "/browse", to: "ideas#index", via: "get"

end

app/models/idea.rb
class Idea < ActiveRecord::Base 
  belongs_to :user
  acts_as_votable

  validates :title, presence: true, length: { minimum: 3, maximum: 128 }
  validates :body, length: { maximum: 12000 }
  
  scope :by_user, -> id { where(user_id: id.to_i ) }

  # @return [Array] A list of Users that voted for this idea
  def voters
    votes.up.by_type(User).voters
  end

  # @return [Fixnum]
  def total_votes
    votes.size
  end

  # Does this idea belong to the passed user?
  # @param [User] user
  def belongs_to_user?(user)
    self.user == user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ideas
  acts_as_voter
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :name,  presence: true, length: { minimum: 3, maximum: 128 },
            format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # I don't like this too much :|
  before_filter :configure_strong_parameters, if: :devise_controller?

  # After sign-in, redirect to the ideas index
  def after_sign_in_path_for(resource)
    browse_path
  end

protected
  def configure_strong_parameters
    # Allow a Display Name to be provided when registering
    devise_parameter_sanitizer.for(:sign_up)        << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  # Allow filtering ideas in a list by a user id:
  has_scope :by_user

  def index
    @ideas  = apply_scopes(Idea)
      .includes(:user, :votes)
      .order("created_at DESC")
      .paginate(page: params[:page], per_page: 10)

    # to-do: #current_scopes can be used to get a list
    # of scopes being used in the index - might be neat
    # to allow toggling these
  end

  def show
    @idea = Idea.find(params[:id])
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = current_user.ideas.build(idea_params)

    if @idea.save
      redirect_to idea_path(@idea), success: "Your idea has been shared!"
    else
      render :new
    end
  end
  
  def vote
    @idea = Idea.find(params[:id])

    # Do not allow a user to vote for his own idea:
    unless current_user == @idea.user
      @idea.vote voter: current_user
    end
  end

protected
  def idea_params
    params.require(:idea).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user  = User.find(params[:id])
    @ideas = @user.ideas.includes(:votes).limit(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include UsersHelper

  # Wrapper around gravatar_image_tag with some more
  # sensible defaults for the application:
  def gravatar_for(user, options={})
    default_class = "gravatar"

    unless options[:class].nil?
      default_class << " #{options[:class]}"
    end

    gravatar_image_tag(
      user.email, alt: user.name, class: default_class,
      gravatar: { size: options[:size] || 32, default: :identicon }
    )
  end

  # Helper for building share-to-twitter links
  # http://twitter.com/home?status=<msg>
  def link_to_share_to_twitter(message, options={}, &block)
    options[:class] = "twitter-link #{options[:class]}"

    message = URI.encode(message)
    link    = "http://twitter.com/home?status=#{message}"

    send(:link_to, link, options, &block)
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_current_user?(user)
    current_user == user
  end
end

app/views/ideas/_idea.html.erb
<% include_author       = true if local_assigns[:include_author].nil?
   this_belongs_to_self = user_signed_in? && idea.belongs_to_user?(current_user)
   self_voted_for_this  = user_signed_in? && current_user.voted_for?(idea) %>

<div class="idea-badge <%= 'idea-belongs-to-self' if this_belongs_to_self %>">
  <div class="idea-votes pull-left <%= 'user-has-voted' if self_voted_for_this %>">
    <div class="js-idea-votes-count" data-idea-id="<%= idea.id %>"><%= idea.total_votes %></div>
    <% unless this_belongs_to_self %>
      <div class="idea-vote-control">

      </div>
    <% end %>
  </div>
  <div class="idea-details">
    <h4 class="idea-title"><%= link_to idea.title, idea %></h4>
    <div class="idea-meta">
      <ul class="list-inline">
        <li class="idea-share-date">
          Shared 
            <% if include_author %>
              by <%= link_to idea.user.name, idea.user %>,
            <% end %>

            <%= distance_of_time_in_words_to_now(idea.created_at) %> ago
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/ideas/index.html.erb
<% content_for :page_title, "Browsing Ideas" %>

<%= render "shared/pagination", object: @ideas %>

<ul class="ideas list-unstyled">
  <%= render @ideas %>
</ul>

<%= render "shared/pagination", object: @ideas %>

app/views/ideas/new.html.erb
<% content_for :page_title, "Share a new Idea" %>

<h1>Share a new Idea:</h1>

<%= simple_form_for(@idea) do |f| %>
  <div class="form-inputs">
    <div class="well">
      <%= f.input :title, label: "Title of your idea", input_html: { class: "input-lg" } %>
    </div>

    <%= f.input :body,  label: "Description of your idea", required: true,
                input_html: { rows: 6 } %>

    <small>
      <%= link_to "Markdown", "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" %>
      is accepted!
    </small>
  </div>

  <div class="form-actions">
    <%= f.submit "Share this idea!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/ideas/show.html.erb
<% content_for :page_title, "#{@idea.title} by #{@idea.user.name}" %>

<div class="idea">
  <header class="idea-header">
    <%= render @idea %>
  </header>

  <div class="row">

    <%# Idea body/markdown content: %>
    <div class="col-md-8">
      <div class="idea-document">
        <% unless @idea.body.empty? %>
          <%= sanitize UnsafeMarkdownPresenter.to_html(@idea.body) %>
        <% else %>
          <em>No description given :(</em>
        <% end %>
      </div>
    </div>

    <%# Sidebar %>
    <div class="col-md-4">

      <div class="idea-actions">
        <% unless @idea.belongs_to_user?(current_user) %>
          <section>
            <h4 class="section-title">Let's try something else...</h4>
            <p class="callout-paragraph">
              Do you want to take this idea in a different direction? Don't like where
              it is going? Copy it to your account and modify it to your liking!
            </p>

            <div class="well text-center">
              <%= link_to "#", class: "btn btn-primary btn-lg" do %>
                <i class="icon-code-fork"></i> Fork this Idea!
              <% end %>
            </div>
          </section>
        <% end %>

        <section>
          <h4 class="section-title">Share</h4>       
          <ul class="idea-social-actions list-inline">
            <%= link_to_share_to_twitter "#{@idea.title} by #{@idea.user.name} @ whatdo: #{idea_url(@idea)}",
                class: "social-badge twitter-social-badge", title: "Tweet this idea" do %>
              <i class="icon-twitter icon-large"></i>
            <% end %>
          </ul>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/ideas/vote.js.erb
// Gotta move this to the interface proper like:
$(".js-vote-callout").attr("disabled", true);
$(".js-idea-votes-count").text(<%= @idea.votes.size %>).parent().addClass("user-has-voted");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>

    <title><%= yield(:page_title) %> | whatdo</title>

    <link rel="stylesheet"
      href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,400italic">
    <link rel="stylesheet"
      href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>
  <body class="application">
    <%= render "shared/report_issues" %>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" unless flash.empty? %>
    
    <% if content_for?(:dont_wrap_content) %>
      <%= yield %>
    <% else %>
      <div class="container">
        <%= yield %>
      </div>
    <% end %>
    
  </body>
</html>

app/views/pages/about.html.erb
Hello :)

app/views/pages/home.html.erb
<% content_for :page_title, "Hi there!" %>
<% provide :dont_wrap_content, true %>

<section class="introduction-banner">
  <div class="container">
    <div class="row introduction-banner-content">
      <div class="col-sm-12">
        <p class="introduction">
          Think better, together.
        </p>

        <div class="user-callout">
          <%= link_to browse_path, class: "btn btn-primary" do %>
            Find Ideas <i class="icon-angle-right"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_flashes.html.erb
<div class="container">
  <ul class="flash-messages list-unstyled">
    <% flash.each do |name, msg| %>
      <%= content_tag :li, msg, class: "alert alert-#{name}" %>
    <% end %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<header class="primary-header">
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <%= link_to "whatdo", root_path, class: "navbar-brand" %>
      </div>

      <div class="site-controls collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Browse Ideas", browse_path %></li>
          <li><%= link_to "Share an Idea", new_idea_path %></li>
        </ul>

        <ul class="user-controls nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <i class="icon-angle-down"></i></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/shared/_pagination.html.erb
<%= will_paginate object, renderer: BootstrapPagination::Rails, bootstrap: 3 %>

app/views/shared/_report_issues.html.erb
<div class="meta-report-issues">
  <%= link_to "https://github.com/filp/whatdo/issues", target: "__blank" do %>
    <i class="icon-github-alt"></i> Report an Issue
  <% end %>
</div>

app/views/users/_tiny_badge.html.erb
<%= link_to user_path(user), title: user.name, class: "user-tiny-badge #{'user-is-self' if is_current_user?(user)}" do %>
  <%= gravatar_for user, size: 36, class: "img-circle" %>
<% end %>

app/views/users/show.html.erb
<% content_for :page_title, @user.name %>

<div class="row">

  <div class="col-sm-3">
    <div class="user-badge text-center">
      <div class="user-avatar">
        <%= link_to @user do %>
          <%= gravatar_for @user, size: 160, class: "img-circle" %> 
        <% end %>
      </div>
      <h2 class="user-name">
        <%= @user.name %>
      </h2>

      <div class="user-meta">
        Member since <%= @user.created_at.to_s(:month_year) %>

        <% if is_current_user?(@user) %>
          <div class="user-actions">
            <ul class="list-inline">
              <li>
                <%= link_to edit_registration_path(current_user), class: "btn btn-xs btn-muted" do %>
                  <i class="icon-code-fork"></i> Edit Profile
              <% end %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-9">
    <% if @ideas.any? %>
      <div class="user-ideas">
        <%= render @ideas, include_author: false %>

        <div class="user-ideas-callout">
          <p>
            <small><%= link_to "View all ideas shared by #{@user.name}", ideas_path(by_user: @user.id) %></small>
          </p>
        </div>
      </div>
    <% else %>
      <small>This user hasn't shared any ideas.</small>
    <% end %>
  </div>
</div>